stages:
  - test
  - build
  - deploy

build:
  stage: build
  image: node:12-alpine

  artifacts:
    paths:
      - front/dist
    expire_in: 2 weeks

  before_script:
    - cd front
    - npm ci

  script:
    - npm run production
