version: "3.7"

services:
  web: &web
    build:
      context: ./app
    env_file: variables.env
    command: uwsgi --ini /usr/src/app/uwsgi.ini
    volumes:
      - ./app/:/usr/src/app/
      - ./static/:/usr/src/app/static
      - ./media/:/usr/src/app/media
    depends_on:
      - db
      - redis

  channelserver:
    <<: *web
    command: daphne --bind 0.0.0.0 --port 5000 -v 1 escriptorium.asgi:application
    expose:
      - 5000

  db:
    image: postgres:10.5-alpine
    volumes:
      - ./postgres/:/var/lib/postgresql/data/
    env_file: variables.env

  redis:
    image: redis:3.0-alpine

  nginx:
    build: ./nginx
    volumes:
      - ./static/:/usr/src/app/static
      - ./media/:/usr/src/app/media
    ports:
      - 8080:80
    depends_on:
      - web

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata/:/usr/share/elasticsearch/data
    #expose:
    #   - 9200
    # ports:
    #  - 9200:9200
    # networks:  # use this if adding nodes
    #   - esnet

  celeryworker:
    build:
      context: ./app
    env_file: variables.env
    depends_on:
      - db
      - redis
    volumes:
      - ./static/:/usr/src/app/static
      - ./media/:/usr/src/app/media
    command: celery multi start 1 -E -A escriptorium -l INFO && celery -E -A escriptorium --concurency 1 -n low-priority -Q low-priority

  celerybeat:
    build:
      context: ./app
    env_file: variables.env
    depends_on:
      - db
      - redis
    volumes:
      - ./static/:/usr/src/app/static
      - ./media/:/usr/src/app/media
    command: celery -E -A escriptorium beat -l INFO

  mail:
    image: elsdoerfer/exim-sender
    expose:
      - 25
    environment:
      - PRIMARY_HOST=escriptorium.fr
      - ALLOWED_HOSTS=localhost ; web ; celeryworker ; docker0
      
# volumes:
#   ./postgres/:
#   ./static/:
#   ./media/:
#   ./esdata/:
#     driver: local