version: "3.7"

services:
  web: &web
    image: lauxley/escriptorium:rc1
    build:
      context: ./app
    env_file: variables.env
    command: uwsgi --ini /usr/src/app/uwsgi.ini
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    depends_on:
      - db
      - redis

  channelserver:
    <<: *web
    image: lauxley/escriptorium:rc1
    command: daphne --bind 0.0.0.0 --port 5000 -v 1 escriptorium.asgi:application
    expose:
      - 5000
    ports:
      - 5000:5000

  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: variables.env

  redis:
    image: redis:3.0-alpine

  nginx:
    image: lauxley/escriptorium/nginx:rc1
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 8080:80
    depends_on:
      - web

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    #expose:
    #   - 9200
    # ports:
    #  - 9200:9200
    # networks:  # use this if adding nodes
    #   - esnet

  celeryworker:
    image: lauxley/escriptorium/cw:rc1
    build:
      context: ./app
    env_file: variables.env
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    command: celery -E -A escriptorium worker -l INFO

  celerybeat:
    image: lauxley/escriptorium/cb:rc1
    build:
      context: ./app
    env_file: variables.env
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    command: celery -E -A escriptorium beat -l INFO

volumes:
  postgres_data:
  static_volume:
  media_volume:
  esdata:
    driver: local