version: "3.7"

services:
  web: &web
    build:
      context: ./app
    env_file: variables.env
    command: uwsgi --ini /usr/src/app/uwsgi.ini
    volumes:
      # - ./app/:/usr/src/app/
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    depends_on:
      - db
      - redis

  channelserver:
    <<: *web
    command: daphne --bind 0.0.0.0 --port 5000 -v 1 escriptorium.asgi:application
    expose:
      - 5000

  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file: variables.env

  redis:
    image: redis:3.0-alpine

  nginx:
    build: ./nginx
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    ports:
      - 8080:80
    depends_on:
      - web

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - ./esdata/:/usr/share/elasticsearch/data
  #   #expose:
  #   #   - 9200
  #   # ports:
  #   #  - 9200:9200
  #   # networks:  # use this if adding nodes
  #   #   - esnet
  
  celery-main: &celery-main
    build:
      context: ./app
    env_file: variables.env
    depends_on:
      - db
      - redis
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    command: "celery worker -l INFO -E -A escriptorium -Q default,img-processing --max-tasks-per-child=10"
  
  celery-low-priority:
    <<: *celery-main
    command: "celery worker -l INFO -E -A escriptorium -Q low-priority -c 2 --max-tasks-per-child=10"

  flower:
    image: mher/flower
    command: ["flower", "--broker=redis://redis:6379/0", "--port=5555"]
    ports:
      - 5555:5555

  # No need while we don't have regular tasks
  # celerybeat:
  #   build:
  #     context: ./app
  #   env_file: variables.env
  #   depends_on:
  #     - db
  #     - redis
  #   volumes:
  #     - ./static/:/usr/src/app/static
  #     - ./media/:/usr/src/app/media
  #     - static:./static/
  #     - media:./media/
  #   command: celery -E -A escriptorium beat -l INFO

  mail:
    image: elsdoerfer/exim-sender
    expose:
      - 25
    environment:
      - PRIMARY_HOST=escriptorium.fr
      - ALLOWED_HOSTS=localhost ; web ; celery-main ; docker0
      
volumes:
   static:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: $PWD/static/
   
   media:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: $PWD/media/
   
   postgres:   
   esdata: