version: "3.9"

services:

  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file: variables.env
    ports:
      - 5432:5432

  redis:
    image: redis:4.0.6-alpine
    ports:
      - 6379:6379

  mail:
    build: ./exim
    image: registry.gitlab.com/scripta/escriptorium/mail
    ports:
      - 25:25
    environment:
      - PRIMARY_HOST=${DOMAIN:-localhost}
      - ALLOWED_HOSTS=web ; celery-main ; celery-low-priority; docker0

volumes:
   static:
   media:
   postgres:
