version: "3.7"

services:
    web: &web
      env_file: production.env
      restart: always

    channelserver:
      env_file: production.env
      restart: always

    db:
      env_file: production.env
      restart: always

    nginx:
      restart: always
      ports:
        - 80:80

    flower:
      restart: always
    
    celery-main:
      env_file: production.env
      restart: always

    celery-low-priority:
      env_file: production.env
      restart: always

     # celerybeat:
     #   env_file: production.env
     #   restart: always
