version: "3.7"

services:
    web: &web
      env_file: production.env
      restart: always

    channelserver:
      env_file: production.env
      restart: always

    db:
      env_file: production.env
      restart: always

    nginx:
      restart: always
      ports:
        - 80:80

    flower:
      restart: always
    
    celery-main:
      env_file: production.env
      restart: always
      depends_on:
        - web
    celery-low-priority:
      env_file: production.env
      restart: always
      depends_on:
        - web
     # celerybeat:
     #   env_file: production.env
     #   restart: always


volumes:
   static:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: $PWD/static/
   
   media:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: $PWD/media/