global:
    scrape_interval: 30s
    evaluation_interval: 5s
    scrape_timeout: 30s

rule_files:
  - "prometheus_rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
    - job_name: monitoring
      static_configs:
        - targets:
            - host.docker.internal
    # - job_name: cadvisor
    #   scrape_interval: 5s
    #   static_configs:
    #     - targets:
    #         - cadvisor:8081
    - job_name: container-exporter
      scrape_interval: 5s
      static_configs:
        - targets:
            - container-exporter:9104
